openapi: 3.0.3
info:
  title: <%= appName %>
  description: <%= appName %>
  version: 1.0.0

paths:
  /foo:
    x-controller: foo
    get:
      x-operation: getFoo
      responses:
        200:
          description: foo bar
          content:
            application/json:
              schema:
                properties:
                  bar:
                    type: string
